version: '3.3'

services:
   minio:
        image: quay.io/minio/minio
        container_name: minio
        restart: on-failure
        command: server /data --address ":9000" --console-address ":9001"
        environment:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: miniopassword
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
          interval: 30s
          timeout: 20s
          retries: 3
        volumes:
          - ./data:/data
        ports:
        - 9000:9000
        - 9001:9001
